### ISSUE TITLE
Search-WebService: Trailing empty characters

### ISSUE THREAD

**Issue by tmgodinho** [bioinformatics-ua/dicoogle#14]
It would be better to remove trailing character from the search webservice response.
Example: 
* "StudyInstanceUID": "1.3.12.2.1107.5.6.1.123.24412.0.231616614823159\u0000\u0000\u0000\u0000\u0000",«
* "SeriesInstanceUID": "1.3.12.2.1107.5.6.1.123.24412.0.231737174002313\u0000\u0000\u0000\u0000\u0000",
* "SOPInstanceUID": "1.3.12.2.1107.5.6.1.123.24412.0.231019730551383\u0000\u0000\u0000\u0000\u0000"

**Comment by Enet4** [comment]
Looks like the original values in the `extraFields` hash map have those trailing null characters, which are not ignored by `net.sf.json`. Is it natural for Lucene or the rest of the Dicoogle core to insert such trailing characters? Nevertheless, could be fixed by mapping all values to its string representation and trimming them before making the object.
