### ISSUE TITLE
web-interface export not responsive

### ISSUE THREAD

**Issue by landge** [bioinformatics-ua/dicoogle#231]
Hi,

I've justed installed dicoogle and tested it with my image repository. The indexing seems to work fantastic!
When I try to export the query results to csv the export button is not responsive! I'm on debian and tried both ice-weasel and chromium. Is there another way to trigger the export. In my case all tags could be 
exported!

Thanks,
landge

**Comment by bastiao** [comment]
Dear Landge, 
thanks for your feedback. Could you please try to give us more details to reproduce it? 
for instance, how many results are you trying to export? and what tags that you're filling to export and how?
Regards,
Luis Bastiao

**Comment by landge** [comment]
I'm trying to export dicom-header information from about 50 MR-brain scans.
The indexing worked fine.
I thought I should begin with just one tag PatientID -- but nothing
happens.

**Comment by bastiao** [comment]
could you try on chrome?
we had an issue with firefox (and probably it happens with other browsers). 
We are planning to fix in the next release.

**Comment by landge** [comment]
Hi,
it works great on chrome!
May I ask you one question concerning the more general implementation of dicoogle in our research setup?
What would you recommend when using dicoogle as an archive server for our postprocessing and analysis pipeline? Is it possible to query dicoogle from python, then retrieve the images into the pipeline directly from python? (when it's possible to get the file locations back from dicoogle!) Or would it be better to insert the indexing into one sql-database and query it from python? I assume that the indexing also works for other fileformats then dicom? I saw different report files indexed.

Thanks for your help and dicoogle.

**Comment by Enet4** [comment]
> Is it possible to query dicoogle from python, then retrieve the images into the pipeline directly from python?

The core of Dicoogle contains a web service for querying the available indices (the endpoint is `/search?query=...`), and also implementents the DICOM Query/Retrieve and Storage protocols. You may call the web service from Python and retrieve the images with a C-MOVE. If you know that all images are kept in your file system, you can take the URI of each search entry and fetch it directly. Otherwise, they will have to be requested from Dicoogle, as it provides an abstraction over storage providers.

We also have a simple Dicoogle Python client [here](https://github.com/bioinformatics-ua/dicoogle-python).

> Or would it be better to insert the indexing into one sql-database and query it from python?

It is usually preferrable to let Dicoogle handle all storage and indexation of all images, thus abstracting from the implementation details and supporting multiple sources of storage and indexing without needing to reimplement anything else. In other words, searching for medical images via Dicoogle works the same whether you have Lucene, MongoDB, MySQL (or any other datbase) serving as the indexer.

> I assume that the indexing also works for other fileformats then dicom? I saw different report files indexed.

Although we have had some research done that involved indexing files that were not DICOM, Dicoogle was mainly designed to store and retrieve DICOM content only.
Technically, this can be circumvented by pushing files into the storage outside of Dicoogle. However, non-DICOM files are not guaranteed to be indexed, and so can not be retrieved by the usual means
(DICOM protocols and services).

See this article for more technical information regarding Dicoogle and its architecture: ["Anatomy of an Extensible Open Source PACS"](http://link.springer.com/article/10.1007/s10278-015-9834-0).

**Comment by landge** [comment]
This sounds really great. I will have a look at the document you linked in your post. 
All our imaging studies are located i our local file system, since we work with sensitive data where everything is uploaded through a file-locker with 2-key authentication. That means well that the URI method should work really fine.  The other file format I thought of is Nifti.
/landge

**Comment by Enet4** [comment]
> The other file format I thought of is Nifti.

I have worked with NIFTI-1 files myself, but I always choose to convert the volume to DICOM whenever I intend to serve them with Dicoogle.

**Comment by landge** [comment]
Hi again,
I've tested the export feature a little bit more in chrome and it seems to work fine for one tag.
Nothing happens when I query multiple tags! What's the correct query-syntax?
One tag per line and no delimiter?

**Comment by landge** [comment]
It's working fine when I access the web-interface from MacOS/Chrome

**Comment by bastiao** [comment]
Something like that: 
```
PatientName
PatientID
InstititutionName
Rows
Columns
```

If you use dicoogle-python, there is also an API for export csv.
