### ISSUE TITLE
Cannot find module 'dicoogle-webcore'

### ISSUE THREAD

**Issue by brajovela** [bioinformatics-ua/dicoogle#253]
*** **Error: Cannot find module 'dicoogle-webcore'.** ***

*If the webapp shows an error due to the dicoogle-webcore package, simply navigate to the webcore package (at the base of the project: "./webcore"), and run npm install there. Then try building the webapp again. * didn't help me

i have npm 2....

**Comment by Enet4** [comment]
If you are trying the master branch, please make sure that `npm install` is called on the webapp after doing the same to webcore. Calling `npm install dicoogle-webcore` and then running the build script might also help.

Since the merge of #233 to our development branch, developers no longer need to worry about dicoogle-webcore when bundling the web application. Therefore, this does not seem to be a current issue with Dicoogle. Please contact us in private if the problem persists.
