### ISSUE TITLE
Expose unindex a file as a web service.

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#38]
Expose the un-index feature through the web service. It was available in version 0.5 and now it is not available anymore. It needs to be re-implemented. 

Requested by Smirnov Denis.

**Comment by Enet4** [comment]
I took a quick shot at the issue, and there you have it in #39. I figured there would be no need to make something too crafty, since the API plugin interfaces could be improved as well (and unindexing is no exception).

On the other hand, this feature will only work if we stop the terrible habit of leaving the plugins' `unindex` operation not implemented. Both the Lucene and CBIR plugins do not implement this method and will throw on invocation. The web service was guarded from runtime exceptions, but I would support making stricter contracts on our plugin interfaces (that we will hopefully achieve with #11).
