### ISSUE TITLE
Creating new user doesn't require authentication

### ISSUE THREAD

**Issue by awdelubi** [bioinformatics-ua/dicoogle#488]
I'd like to install dicoogle in an Internet facing environment. According to the documentation https://bioinformatics-ua.github.io/dicoogle-api/webapi/, the "createUser" option doesn't require authentication. It seems anyone can create an admin user as long as the endpoint is known. This is unsecure in a public Internet facing environment.

Is there any reason it doesn't require authentication or am I missing something?

**Comment by Enet4** [comment]
Hello @awdelubi. Yes, Dicoogle has a very thin layer of access control, which is currently used merely for limiting access to operations through the web user interface. In practice, the archive component is not meant to be public-facing, which is why there isn't a need for complete RBAC coverage.

Ideas for making access control secure and more reliable are filed in #98. But until then, one may try deploying an intermediate server with controlled access to the archive's web services. BMD Software has a high quality commercial solution for this, should this be a possibility to your use case.

**Comment by awdelubi** [comment]
Thank you @Enet4. Will close the issue.
