### ISSUE TITLE
Build the parent Maven project hands-on

### ISSUE THREAD

**Issue by Shawa07** [bioinformatics-ua/dicoogle#609]
I am trying to install maven on windows 10 using Visual Studio Code, but I am currently facing an error when I run the code:

`mvn install`

I get the error below:
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.0:npm (npm install) on project dicoogle: Failed to run
 task: 'npm install --no-audit' failed. java.io.IOException: Cannot run program "C:\Users\pc\Desktop\DICOOGLE\dicoogle\dicoogle\targ
et\node\node.exe" (in directory "C:\Users\pc\Desktop\DICOOGLE\dicoogle\dicoogle\src\main\resources\webapp"): CreateProcess error=193
, %1 is not a valid Win32 application -> [Help 1]

**Comment by Enet4** [comment]
Here are some tips for troubleshooting:

- Try cleaning up the project with `mvn clean` and running `mvn install` again.
- Is it the Windows 64-bit or 32-bit? There might not be great support for 32-bit Windows at this time.
- If you already have Node.js LTS on your machine, the automatic webapp construction step can be skipped so that you may [build it yourself](https://bioinformatics-ua.github.io/dicoogle-learning-pack/docs/building/).

```
cd dicoogle/src/main/resources/webapp
npm i
cd ../../../../..
mvn install -Dskip.installnodenpm -Dskip.npm
```
