### ISSUE TITLE
dump endpoint doest dump all DICOM info 

### ISSUE THREAD

**Issue by beavermml** [bioinformatics-ua/dicoogle#619]
i have a DX dicom image and when i use the /dump endpoint.. it doesnt dump all the data..

i only get around 29 data
![image](https://user-images.githubusercontent.com/3795219/198540548-9095dc02-8e08-4cd0-813d-c0fbce467072.png)

but when checking using MicroDicomViewer i get a lot more

![image](https://user-images.githubusercontent.com/3795219/198540678-b361ac7a-591d-48aa-aa6f-7216578ba2dc.png)

since im using OHIF HTML5 Viewer, i need that metadata information to pass to so that it can be properly show

**Comment by Enet4** [comment]
Thank you for reporting. As currently designed, the dump operation only provides _indexed_ meta-data. It is possible to configure the system to index all known meta-data by enabling this for each modality intended, in `tags.xml`:

```xml
<Tags>
...
<modalities enable="true" all="false">
  <!-- index all meta-data -->
  <modality enable="true" all="true" id="DX"/>
</modalities>
...
</Tags>
```

After unindexing the file and indexing it again, more attributes should appear.

When more than this is required, one might be better served with a WADO service extension, so that the whole file can be fetched and dumped.
