### ISSUE TITLE
Improve the deployment approach (mvn build/install) 

### ISSUE THREAD

**Issue by bastiao** [bioinformatics-ua/dicoogle#63]
By default, including all node_modules dependencies is quite heavy and time spending.

**Comment by Enet4** [comment]
`devDependencies` are only needed for building the application, whereas the other ones are required for the deployment. I've seen some dependencies in the web app being incorrectly assigned as common dependencies when they are actually dev dependencies.
Are you suggesting to include the web app's building script into the maven processes?

**Comment by bastiao** [comment]
yes, it is one possibility, with grunt plugin or whatever. But for now, we need to evaluate the best way to do it.

**Comment by Enet4** [comment]
We may discuss this tomorrow. But since we have a prepublish script,
performing an npm install from maven is enough to build it. Deploying it
would then involve pruning the dependencies.
And it seems a maven plugin is available.
https://github.com/eirslett/frontend-maven-plugin

Eduardo Pinho
http://enet4.wordpress.com

2015-06-12 0:07 GMT+01:00 Luís Bastião <notifications@github.com>:

**Comment by Enet4** [comment]
The [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) requires that Node.js and npm are installed locally. I find it overkill for development purposes, but then it would work on any machine with Maven.
Alternatively, we could just use mojo to execute `npm`. So what do you think? And by the way, how should we separate the Java source building process with the web app's?
