### ISSUE TITLE
How to display thumbnail images

### ISSUE THREAD

**Issue by Whiteyingshan** [bioinformatics-ua/dicoogle#703]
Please help me, there is currently a DICOM file that does not display thumbnails in this project, but can be viewed using DICOM VIEWER（https://milung.github.io/dicom-editor/dist/）. 
I am currently using the default configuration, how can I make it display thumbnails?
![1730429098452](https://github.com/user-attachments/assets/e4b1772c-7a97-4fc2-9c33-41a8b078f814)
![1730428911604](https://github.com/user-attachments/assets/529ea035-fa27-422a-943b-ccc3305a6e76)

Here is my DICOM file
[1.2.392.200036.9125.0.19950720112207.zip](https://github.com/user-attachments/files/17595370/1.2.392.200036.9125.0.19950720112207.zip)

**Comment by Enet4** [comment]
A thumbnail not appearing could be caused by a number of reasons. I would recommend inspecting the logs for a more specific.

Seeing that you sent us a pull request (thank you!), it may have to do with the missing DIM provider specification in the server configuration. `confs/server.xml` should have something like this (I suppose the documentation is not very clear about this):

```xml
<config>
  <archive>
    <!-- ... ->
    <dim-providers>
      <dim-provider>lucene</dim-provider>
    </dim-providers>
  </archive>
  <!-- ... -->
```
